### ISSUE TITLE
epub support

### ISSUE THREAD

**Issue by jaan143** [evmer/scribd-downloader#1]
Thank you very much for this script but please add code for epub conversion which will more easy for users 
you can get help of epub conversion code from here 
https://github.com/ilyakharlamov/bookmate_downloader 

inside this you will see bookmate_downloader.py where epub conversion code placed.

once again thank you very much for this amazing project.
i am the first who gave you star :)
Cheers

**Comment by jaan143** [comment]
@evmer  please add Requirements.txt file with dependencies

**Comment by evmer** [comment]
Hey @jaan143 I've already added the epub confersion to the TODO.

I don't think requirements.txt is useful here since there are just 2 requirements, just install them separately
