### ISSUE TITLE
'charmap' codec can't encode character

### ISSUE THREAD

**Issue by jaan143** [evmer/scribd-downloader#2]
please see this error

PS C:\Users\Hp\Downloads\Compressed\scribd-downloader-main_4\scribd-downloader-main> python run.py https://www.scribd.com/book/553564243/Digital-Capitalism-and-Distributive-Forces
Logged in successfully.
Loading viewer...
Downloading chapter 1/44 (1 pages)
Downloading chapter 2/44 (1 pages)
Downloading chapter 3/44 (1 pages)
Downloading chapter 4/44 (1 pages)
Downloading chapter 5/44 (3 pages)
Traceback (most recent call last):
  File "C:\Users\Hp\Downloads\Compressed\scribd-downloader-main_4\scribd-downloader-main\run.py", line 113, in <module>
    f.write(content)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2074' in position 43875: character maps to <undefined>
PS C:\Users\Hp\Downloads\Compressed\scribd-downloader-main_4\scribd-downloader-main>

**Comment by evmer** [comment]
Thank you for reporting this to me. It should be fixed now, please re-download the script

**Comment by evmer** [comment]
@jaan143 the pdf page size is the same as the one rendered on Scribd web reader, i.e. should match perfectly

but yes we can scale it to decrease the PDF size, I just need some more testing to figure out the right %

added to the TODO 🫡, this is a easy one, expect it to be implemented v soon

**Comment by jaan143** [comment]
@evmer  i am sorry to asking that question
i don't understand about TODO 
TODO means anyone can do this or you will add this features in future ?

**Comment by evmer** [comment]
Both, this is Github and everybody can contribute

**Comment by jaan143** [comment]
@evmer  if we see the structure of scribd books it is looks like Epub format
so i think it will more perfect and fit if we convert html to epub 
i hope this feature will be available later on.
